; This is the roster of allowed units for the player in the campaign - this is built off real units that were in the Pacific in June 1985
; Task Force Builder will check this file first to ensure the unit is an allowed unit, then filter further down if the mission has an allowlist

; unit short descriptions (gameplay focused) are now handled per-unit/per-language in unit_roster_descriptions_<lang>.ini


[AllowedVessels]
; syntax is: <unit_type>=<variant_number>,<variant_number>,<variant_number>|<points_cost>

wp_rkr_kirov=Variant1|750
wp_rkr_slava=Variant2,Variant3|400
wp_takr_kiev=Variant3|360
wp_kr_sverdlov=Variant5,Variant6,Variant7,Variant10|230
wp_bpk_kara=Variant1,Variant4,Variant5,Variant6|250
wp_bpk_kresta2=Variant8,Variant9,Variant10|215
wp_rkr_kresta1=Variant2,Variant4|225
wp_rkr_kynda=Variant2,Variant4|200
wp_em_sovremenny=Variant1,Variant2,Variant3,Variant4,Variant6,Variant7,Variant9,Variant11,Variant13|235
wp_bpk_udaloy=Variant1,Variant2,Variant4,Variant5,Variant6,Variant7,Variant10,Variant12|280
wp_bpk_kashin=Variant6,Variant16,Variant17,Variant18|95
wp_bpk_kanin=Variant5,Variant6,Variant8|75
wp_skr_krivak2=Variant1,Variant4,Variant7,Variant8,Variant9,Variant10,Variant11|110
wp_skr_krivak1=Variant7,Variant8,Variant9,Variant12,Variant17|80


[AllowedSubmarines]
; Note: subs are currently not available for purchase in Pacific Strike campaign due to mission-level allowlisting removing them.
; syntax is: <unit_type>=<variant_number>,<variant_number>,<variant_number>|<points_cost>


[LoadoutPrices]
; syntax is: <unit_type>=<loadout_name>,<points_cost>|<loadout_name>,<points_cost>
; aircraft loadouts are included in the aircraft purchase cost


[AllowedHelicopters]
; syntax for aircraft is: <unit_type>=<squadron_number>,<squadron_number>|<points_cost_per_aircraft>

wp_ka-25=Squadron1|20
wp_ka-25ts=Squadron3,Squadron4|45
wp_ka-27=Squadron3,Squadron4,Squadron7|60
wp_ka-29=Squadron3|58


[AllowedAircraft]
; syntax for aircraft is: <unit_type>=<squadron_number>,<squadron_number>|<points_cost_per_aircraft>

wp_yak-38=Squadron3,Squadron4|25
wp_mig-23a=Squadron3|55
wp_mig-25pd=Squadron1|85
wp_su-24m=Squadron2|78
wp_il-38=Squadron3|60
wp_tu-95rt=Squadron3|85
wp_tu-16k=Squadron11|120
wp_tu-22m2=Squadron8|210
wp_tu-16p=Squadron6|160
wp_p-42_rldn=Squadron2|420